spring.application.name=gms-bank

spring.datasource.url=jdbc:postgresql://localhost:5432/fincore_db
spring.datasource.username=postgres
spring.datasource.password=221019
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

server.port=8081